<a href="https://colab.research.google.com/github/piyushchand16/Python/blob/main/Python_Basics_and_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics


In [ ]:
a=50

In [ ]:
a

50

In [ ]:
if(a>100):
  print("Bigger than 100")
elif(a>=50):
  print("bigger than equal to 50")
else:
  print("smaller than 50")

bigger than equal to 50


In [ ]:
a=60

In [ ]:
def addition(a,b):
  return a+b

In [ ]:
addition(5,2)

7

In [ ]:
addition(6.3,5.6)

11.899999999999999

In [ ]:
def getInteger():
  return int(input("enter the number"))

def Main():
  print("main function started")
  print(getInteger())

if __name__=="__main__":
  Main()

main function started
enter the number4
4


**range function**

In [ ]:
for i in range(1,10):
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(2,10,3):
  print(i)

2
5
8


**Make a Basic Calculator**

In [ ]:
n1=int(input("Enter the First Number"))
n2=int(input("Enter the Second Number"))
opr=input("Enter the number for the opertion 1 for +, 2 for -, 3 for multiply, 4 for divide")
if(opr=="1"):
  ans=n1+n2
  print("The answer is",ans)
elif(opr=="2"):
  ans=n1-n2
  print("The answer is",ans)
elif(opr=="3"):
  ans=n1*n2
  print("The answer is",ans)
elif(opr=="4"):
  if(n2==0):
    print("sorry,division is not possible, check with other numbers")
  else:
    ans=n1/n2
    print("The answer is",ans)
else:
  print("Invalid operator")


Enter the First Number2
Enter the Second Number0
Enter the number for the opertion 1 for +, 2 for -, 3 for multiply, 4 for divide4
sorry,division is not possible, check with other numbers


# Numpy


In [1]:
import numpy as np

numpy arrays:Vectors(1 D Array)and Matrices(2d arrays)

In [ ]:
# rank 1 array
np.array([1,4,7,9])

array([1, 4, 7, 9])

In [ ]:
#rank 2 array
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
lis=[1,2,3]

In [ ]:
np.array(lis)

array([1, 2, 3])

In [ ]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Built in Methods**

arange

arange(stop)

arange(start,stop)

arange(start,stop,step)

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2,10,3)

array([2, 5, 8])

Zeroes and Ones

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

np.ones(5)

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

linspace

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

eye -makes identity matrix 1 in diagonal

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Array Attributes and Mathods**

In [2]:
x=np.arange(25)

In [ ]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
x.max()

24

In [ ]:
x[24]=100

NameError: ignored

In [ ]:
x

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23, 100])

In [ ]:
x.argmax()

24

In [ ]:
x.min()

0

In [ ]:
x.argmin()

0

In [ ]:
x.shape

NameError: ignored

In [ ]:
x=x.reshape(1,25)

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
x=x.reshape(25,1)

In [ ]:
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
type(x)

numpy.ndarray

**Bracket Indexing and Selection**

In [ ]:
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
x[0]

array([0])

In [3]:
x[0:4]

array([0, 1, 2, 3])

Broadcasting

In [4]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [7]:
x[0:5]=100

In [8]:
x

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [10]:
slice_of_x=x[0:5]

In [11]:
slice_of_x

array([100, 100, 100, 100, 100])

In [12]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
y[1:3,0:2]

array([[4, 5],
       [7, 8]])

**Selection**

In [16]:
x

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [17]:
x>95

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [18]:
z=x>95

In [19]:
z

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [20]:
x[z]

array([100, 100, 100, 100, 100])

In [21]:
x[x>99]

array([100, 100, 100, 100, 100])

In [22]:
x

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [24]:
x+x

array([200, 200, 200, 200, 200,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48])

In [25]:
np.sqrt(x)

array([10.        , 10.        , 10.        , 10.        , 10.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894,
        4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949])

In [27]:
np.exp(x)

array([2.68811714e+43, 2.68811714e+43, 2.68811714e+43, 2.68811714e+43,
       2.68811714e+43, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10])